package com.bfuture.app.saas.model.report;

// Generated 2011-12-7 14:38:38 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * YwGoodssaleId generated by hbm2java
 */
@Embeddable
public class YwGoodssaleId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3945233244142460004L;
	private String gssgcode;
	private String gssupid;
	private Date gsrq;
	private String gsgdid;
	private String gsmfid;
	private String gsgz;

	public YwGoodssaleId() {
	}

	public YwGoodssaleId(String gssgcode, String gssupid, Date gsrq,
			String gsgdid, String gsmfid, String gsgz) {
		this.gssgcode = gssgcode;
		this.gssupid = gssupid;
		this.gsrq = gsrq;
		this.gsgdid = gsgdid;
		this.gsmfid = gsmfid;
		this.gsgz = gsgz;
	}

	@Column(name = "GSSGCODE", nullable = false, length = 30)
	public String getGssgcode() {
		return this.gssgcode;
	}

	public void setGssgcode(String gssgcode) {
		this.gssgcode = gssgcode;
	}

	@Column(name = "GSSUPID", nullable = false, length = 24)
	public String getGssupid() {
		return this.gssupid;
	}

	public void setGssupid(String gssupid) {
		this.gssupid = gssupid;
	}

	@Column(name = "GSRQ", nullable = false, length = 7)
	public Date getGsrq() {
		return this.gsrq;
	}

	public void setGsrq(Date gsrq) {
		this.gsrq = gsrq;
	}

	@Column(name = "GSGDID", nullable = false, length = 24)
	public String getGsgdid() {
		return this.gsgdid;
	}

	public void setGsgdid(String gsgdid) {
		this.gsgdid = gsgdid;
	}

	@Column(name = "GSMFID", nullable = false, length = 30)
	public String getGsmfid() {
		return this.gsmfid;
	}

	public void setGsmfid(String gsmfid) {
		this.gsmfid = gsmfid;
	}

	@Column(name = "GSGZ", nullable = false, length = 30)
	public String getGsgz() {
		return this.gsgz;
	}

	public void setGsgz(String gsgz) {
		this.gsgz = gsgz;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof YwGoodssaleId))
			return false;
		YwGoodssaleId castOther = (YwGoodssaleId) other;

		return ((this.getGssgcode() == castOther.getGssgcode()) || (this
				.getGssgcode() != null
				&& castOther.getGssgcode() != null && this.getGssgcode()
				.equals(castOther.getGssgcode())))
				&& ((this.getGssupid() == castOther.getGssupid()) || (this
						.getGssupid() != null
						&& castOther.getGssupid() != null && this.getGssupid()
						.equals(castOther.getGssupid())))
				&& ((this.getGsrq() == castOther.getGsrq()) || (this.getGsrq() != null
						&& castOther.getGsrq() != null && this.getGsrq()
						.equals(castOther.getGsrq())))
				&& ((this.getGsgdid() == castOther.getGsgdid()) || (this
						.getGsgdid() != null
						&& castOther.getGsgdid() != null && this.getGsgdid()
						.equals(castOther.getGsgdid())))
				&& ((this.getGsmfid() == castOther.getGsmfid()) || (this
						.getGsmfid() != null
						&& castOther.getGsmfid() != null && this.getGsmfid()
						.equals(castOther.getGsmfid())))
				&& ((this.getGsgz() == castOther.getGsgz()) || (this.getGsgz() != null
						&& castOther.getGsgz() != null && this.getGsgz()
						.equals(castOther.getGsgz())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGssgcode() == null ? 0 : this.getGssgcode().hashCode());
		result = 37 * result
				+ (getGssupid() == null ? 0 : this.getGssupid().hashCode());
		result = 37 * result
				+ (getGsrq() == null ? 0 : this.getGsrq().hashCode());
		result = 37 * result
				+ (getGsgdid() == null ? 0 : this.getGsgdid().hashCode());
		result = 37 * result
				+ (getGsmfid() == null ? 0 : this.getGsmfid().hashCode());
		result = 37 * result
				+ (getGsgz() == null ? 0 : this.getGsgz().hashCode());
		return result;
	}

}
