package com.bfuture.app.saas.model.report;

// Generated 2011-12-7 14:38:38 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.bfuture.app.basic.model.BaseObject;

/**
 * YwGoodssale generated by hbm2java
 */
@Entity
@Table(name = "YW_GOODSSALE")
public class YwGoodssale extends BaseObject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4121974411992879247L;
	private YwGoodssaleId id;
	private BigDecimal gsxssl;  	// 销售数量
	private BigDecimal gsxssr;		// 实际销售金额
	private BigDecimal gsxsje;		// 售价金额（实际销售金额+折扣金额）
	private BigDecimal gshsjjje;	// 含税进价金额
	private BigDecimal gsrebate;	// 折扣金额（供应商承担折扣+厂商承担折扣）
	private BigDecimal gsvendrebate;	// 供应商承担折扣
	private BigDecimal gsmanrebate;		// 厂商承担折扣
	private String temp1;
	private BigDecimal temp2;
	private BigDecimal temp3;
	private String temp4;
	private String temp5;
	private Date gsgxtime;	// 创建日期
	private String gsfile;	// 导入文件名
	
	private String gssgcode; // 实例编码
	private String gssupid;  // 供应商编码
	private Date gsrq;		 // 日期
	private String gsgdid;	 // 商品编码
	private String gsmfid;	 // 门店编码
	private String gsgz;	 // 柜组

	// 辅助
	private String isSup;
	private String sucode;
	private String startDate;  // 起始时间
	private String endDate;    // 结束时间
	private String saleObject; // 销售对象
	private String ppname;
	
	public YwGoodssale() {
	}

	public YwGoodssale(YwGoodssaleId id) {
		this.id = id;
	}

	public YwGoodssale(YwGoodssaleId id, BigDecimal gsxssl, BigDecimal gsxssr,
			BigDecimal gsxsje, BigDecimal gshsjjje, BigDecimal gsrebate,
			BigDecimal gsvendrebate, BigDecimal gsmanrebate, String temp1,
			BigDecimal temp2, BigDecimal temp3, String temp4, String temp5,
			Date gsgxtime, String gsfile) {
		this.id = id;
		this.gsxssl = gsxssl;
		this.gsxssr = gsxssr;
		this.gsxsje = gsxsje;
		this.gshsjjje = gshsjjje;
		this.gsrebate = gsrebate;
		this.gsvendrebate = gsvendrebate;
		this.gsmanrebate = gsmanrebate;
		this.temp1 = temp1;
		this.temp2 = temp2;
		this.temp3 = temp3;
		this.temp4 = temp4;
		this.temp5 = temp5;
		this.gsgxtime = gsgxtime;
		this.gsfile = gsfile;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "gssgcode", column = @Column(name = "GSSGCODE", nullable = false, length = 30)),
			@AttributeOverride(name = "gssupid", column = @Column(name = "GSSUPID", nullable = false, length = 24)),
			@AttributeOverride(name = "gsrq", column = @Column(name = "GSRQ", nullable = false, length = 7)),
			@AttributeOverride(name = "gsgdid", column = @Column(name = "GSGDID", nullable = false, length = 24)),
			@AttributeOverride(name = "gsmfid", column = @Column(name = "GSMFID", nullable = false, length = 30)),
			@AttributeOverride(name = "gsgz", column = @Column(name = "GSGZ", nullable = false, length = 30)) })
	public YwGoodssaleId getId() {
		return this.id;
	}

	public void setId(YwGoodssaleId id) {
		this.id = id;
	}

	@Column(name = "GSXSSL", precision = 22, scale = 0)
	public BigDecimal getGsxssl() {
		return this.gsxssl;
	}

	public void setGsxssl(BigDecimal gsxssl) {
		this.gsxssl = gsxssl;
	}

	@Column(name = "GSXSSR", precision = 16)
	public BigDecimal getGsxssr() {
		return this.gsxssr;
	}

	public void setGsxssr(BigDecimal gsxssr) {
		this.gsxssr = gsxssr;
	}

	@Column(name = "GSXSJE", precision = 16)
	public BigDecimal getGsxsje() {
		return this.gsxsje;
	}

	public void setGsxsje(BigDecimal gsxsje) {
		this.gsxsje = gsxsje;
	}

	@Column(name = "GSHSJJJE", precision = 16)
	public BigDecimal getGshsjjje() {
		return this.gshsjjje;
	}

	public void setGshsjjje(BigDecimal gshsjjje) {
		this.gshsjjje = gshsjjje;
	}

	@Column(name = "GSREBATE", precision = 16)
	public BigDecimal getGsrebate() {
		return this.gsrebate;
	}

	public void setGsrebate(BigDecimal gsrebate) {
		this.gsrebate = gsrebate;
	}

	@Column(name = "GSVENDREBATE", precision = 16)
	public BigDecimal getGsvendrebate() {
		return this.gsvendrebate;
	}

	public void setGsvendrebate(BigDecimal gsvendrebate) {
		this.gsvendrebate = gsvendrebate;
	}

	@Column(name = "GSMANREBATE", precision = 16)
	public BigDecimal getGsmanrebate() {
		return this.gsmanrebate;
	}

	public void setGsmanrebate(BigDecimal gsmanrebate) {
		this.gsmanrebate = gsmanrebate;
	}

	@Column(name = "TEMP1", length = 30)
	public String getTemp1() {
		return this.temp1;
	}

	public void setTemp1(String temp1) {
		this.temp1 = temp1;
	}

	@Column(name = "TEMP2", precision = 16)
	public BigDecimal getTemp2() {
		return this.temp2;
	}

	public void setTemp2(BigDecimal temp2) {
		this.temp2 = temp2;
	}

	@Column(name = "TEMP3", precision = 16)
	public BigDecimal getTemp3() {
		return this.temp3;
	}

	public void setTemp3(BigDecimal temp3) {
		this.temp3 = temp3;
	}

	@Column(name = "TEMP4", length = 30)
	public String getTemp4() {
		return this.temp4;
	}

	public void setTemp4(String temp4) {
		this.temp4 = temp4;
	}

	@Column(name = "TEMP5", length = 30)
	public String getTemp5() {
		return this.temp5;
	}

	public void setTemp5(String temp5) {
		this.temp5 = temp5;
	}

	@Column(name = "GSGXTIME")
	public Date getGsgxtime() {
		return this.gsgxtime;
	}

	public void setGsgxtime(Date gsgxtime) {
		this.gsgxtime = gsgxtime;
	}

	@Column(name = "GSFILE", length = 64)
	public String getGsfile() {
		return this.gsfile;
	}

	public void setGsfile(String gsfile) {
		this.gsfile = gsfile;
	}
	
	@Transient
	public String getGssgcode() {
		return gssgcode;
	}

	public void setGssgcode(String gssgcode) {
		this.gssgcode = gssgcode;
	}

	@Transient
	public String getGssupid() {
		return gssupid;
	}

	public void setGssupid(String gssupid) {
		this.gssupid = gssupid;
	}

	@Transient
	public Date getGsrq() {
		return gsrq;
	}

	public void setGsrq(Date gsrq) {
		this.gsrq = gsrq;
	}

	@Transient
	public String getGsgdid() {
		return gsgdid;
	}

	public void setGsgdid(String gsgdid) {
		this.gsgdid = gsgdid;
	}

	@Transient
	public String getGsmfid() {
		return gsmfid;
	}

	public void setGsmfid(String gsmfid) {
		this.gsmfid = gsmfid;
	}

	@Transient
	public String getGsgz() {
		return gsgz;
	}

	public void setGsgz(String gsgz) {
		this.gsgz = gsgz;
	}
	
	@Transient
	public String getIsSup() {
		return isSup;
	}

	public void setIsSup(String isSup) {
		this.isSup = isSup;
	}

	@Transient
	public String getSucode() {
		return sucode;
	}

	public void setSucode(String sucode) {
		this.sucode = sucode;
	}

	@Transient
	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	@Transient
	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	@Transient
	public String getSaleObject() {
		return saleObject;
	}

	public void setSaleObject(String saleObject) {
		this.saleObject = saleObject;
	}

	@Transient
	public String getPpname() {
		return ppname;
	}

	public void setPpname(String ppname) {
		this.ppname = ppname;
	}

	@Override
	public boolean equals(Object o) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public int hashCode() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return null;
	}

}
