package com.bfuture.app.saas.model;

// Generated 2011-12-7 14:38:38 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InfGoodsuplyId generated by hbm2java
 */
@Embeddable
public class InfGoodsuplyId implements java.io.Serializable {

	private String gssgcode;
	private String gsid;
	private String gssupid;
	private String gsmfid;

	public InfGoodsuplyId() {
	}

	public InfGoodsuplyId(String gssgcode, String gsid, String gssupid,
			String gsmfid) {
		this.gssgcode = gssgcode;
		this.gsid = gsid;
		this.gssupid = gssupid;
		this.gsmfid = gsmfid;
	}

	@Column(name = "GSSGCODE", nullable = false, length = 30)
	public String getGssgcode() {
		return this.gssgcode;
	}

	public void setGssgcode(String gssgcode) {
		this.gssgcode = gssgcode;
	}

	@Column(name = "GSID", nullable = false, length = 24)
	public String getGsid() {
		return this.gsid;
	}

	public void setGsid(String gsid) {
		this.gsid = gsid;
	}

	@Column(name = "GSSUPID", nullable = false, length = 30)
	public String getGssupid() {
		return this.gssupid;
	}

	public void setGssupid(String gssupid) {
		this.gssupid = gssupid;
	}

	@Column(name = "GSMFID", nullable = false, length = 30)
	public String getGsmfid() {
		return this.gsmfid;
	}

	public void setGsmfid(String gsmfid) {
		this.gsmfid = gsmfid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InfGoodsuplyId))
			return false;
		InfGoodsuplyId castOther = (InfGoodsuplyId) other;

		return ((this.getGssgcode() == castOther.getGssgcode()) || (this
				.getGssgcode() != null
				&& castOther.getGssgcode() != null && this.getGssgcode()
				.equals(castOther.getGssgcode())))
				&& ((this.getGsid() == castOther.getGsid()) || (this.getGsid() != null
						&& castOther.getGsid() != null && this.getGsid()
						.equals(castOther.getGsid())))
				&& ((this.getGssupid() == castOther.getGssupid()) || (this
						.getGssupid() != null
						&& castOther.getGssupid() != null && this.getGssupid()
						.equals(castOther.getGssupid())))
				&& ((this.getGsmfid() == castOther.getGsmfid()) || (this
						.getGsmfid() != null
						&& castOther.getGsmfid() != null && this.getGsmfid()
						.equals(castOther.getGsmfid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGssgcode() == null ? 0 : this.getGssgcode().hashCode());
		result = 37 * result
				+ (getGsid() == null ? 0 : this.getGsid().hashCode());
		result = 37 * result
				+ (getGssupid() == null ? 0 : this.getGssupid().hashCode());
		result = 37 * result
				+ (getGsmfid() == null ? 0 : this.getGsmfid().hashCode());
		return result;
	}

}
