package com.bfuture.app.saas.model;

// Generated 2011-12-7 14:38:38 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.bfuture.app.basic.model.BaseObject;

/**
 * InfGoodsId generated by hbm2java
 */
@Embeddable
public class InfGoodsId extends BaseObject implements java.io.Serializable {

	private String gdsgcode; // 实例编码
	private String gdid; 	 // 商品编码

	public InfGoodsId() {
	}

	public InfGoodsId(String gdsgcode, String gdid) {
		this.gdsgcode = gdsgcode;
		this.gdid = gdid;
	}

	@Column(name = "GDSGCODE", nullable = false, length = 30)
	public String getGdsgcode() {
		return this.gdsgcode;
	}

	public void setGdsgcode(String gdsgcode) {
		this.gdsgcode = gdsgcode;
	}

	@Column(name = "GDID", nullable = false, length = 24)
	public String getGdid() {
		return this.gdid;
	}

	public void setGdid(String gdid) {
		this.gdid = gdid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InfGoodsId))
			return false;
		InfGoodsId castOther = (InfGoodsId) other;

		return ((this.getGdsgcode() == castOther.getGdsgcode()) || (this
				.getGdsgcode() != null
				&& castOther.getGdsgcode() != null && this.getGdsgcode()
				.equals(castOther.getGdsgcode())))
				&& ((this.getGdid() == castOther.getGdid()) || (this.getGdid() != null
						&& castOther.getGdid() != null && this.getGdid()
						.equals(castOther.getGdid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGdsgcode() == null ? 0 : this.getGdsgcode().hashCode());
		result = 37 * result
				+ (getGdid() == null ? 0 : this.getGdid().hashCode());
		return result;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return null;
	}

}
