package com.bfuture.app.saas.model;

// Generated 2011-12-7 14:38:38 by Hibernate Tools 3.2.2.GA

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.bfuture.app.basic.model.BaseObject;

/**
 * InfGoods generated by hbm2java
 */
@Entity
@Table(name = "INF_GOODS")
public class InfGoods extends BaseObject implements java.io.Serializable {
	
	private InfGoodsId id;		// 实例编码(gdsgcode) 商品编码(gdid)
	private String gdname; 		// 商品名称
	private String gdbarcode;   // 商品条码
	private String gdcatid;     // 商品类别编码
	private String gdcatname;   // 商品类别名称
	private String gdppname;	// 品牌名称
	private String gdspec;      // 规格
	private BigDecimal gdtax;	// 税率
	private String gdarea;		// 产地
	private String gdunit; 		// 单位
	private String gdcshh;
	private String temp1;
	private String temp2;
	private String temp3;
	private String temp4;
	private String temp5;
	private Serializable gdgxtime;
	private String gdfile;
	
	



	public InfGoods(InfGoodsId id, String gdname, String gdbarcode,
			String gdppname, String gdid) {
		super();
		this.id = id;
		this.gdname = gdname;
		this.gdbarcode = gdbarcode;
		this.gdppname = gdppname;
		this.gdid = gdid;
	}

	


	private String gdsgcode; // 实例编码
	private String gdid; 	 // 商品编码
	private String gssupid;
	private String supcode;
	private String sgcode;
	
	

	public String getSgcode() {
		return sgcode;
	}

	public void setSgcode(String sgcode) {
		this.sgcode = sgcode;
	}

	
	public InfGoods(InfGoodsId id, String gdname, String gdbarcode,
			String gdcatid, String gdcatname, String gdppname, String gdspec,
			BigDecimal gdtax, String gdarea, String gdunit, String gdcshh,
			String temp1, String temp2, String temp3, String temp4,
			String temp5, Serializable gdgxtime, String gdfile,
			String gdsgcode, String gdid, String gssupid, String supcode,
			String sgcode) {
		super();
		this.id = id;
		this.gdname = gdname;
		this.gdbarcode = gdbarcode;
		this.gdcatid = gdcatid;
		this.gdcatname = gdcatname;
		this.gdppname = gdppname;
		this.gdspec = gdspec;
		this.gdtax = gdtax;
		this.gdarea = gdarea;
		this.gdunit = gdunit;
		this.gdcshh = gdcshh;
		this.temp1 = temp1;
		this.temp2 = temp2;
		this.temp3 = temp3;
		this.temp4 = temp4;
		this.temp5 = temp5;
		this.gdgxtime = gdgxtime;
		this.gdfile = gdfile;
		this.gdsgcode = gdsgcode;
		this.gdid = gdid;
		this.gssupid = gssupid;
		this.supcode = supcode;
		this.sgcode = sgcode;
	}

	public String getSupcode() {
		return supcode;
	}

	public void setSupcode(String supcode) {
		this.supcode = supcode;
	}

	

	public String getGssupid() {
		return gssupid;
	}

	public void setGssupid(String gssupid) {
		this.gssupid = gssupid;
	}

	public InfGoods() {
	}

	public InfGoods(InfGoodsId id) {
		this.id = id;
	}

	

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "gdsgcode", column = @Column(name = "GDSGCODE", nullable = false, length = 30)),
			@AttributeOverride(name = "gdid", column = @Column(name = "GDID", nullable = false, length = 24)) })
	public InfGoodsId getId() {
		return this.id;
	}

	public void setId(InfGoodsId id) {
		this.id = id;
	}

	@Column(name = "GDNAME", length = 80)
	public String getGdname() {
		return this.gdname;
	}

	public void setGdname(String gdname) {
		this.gdname = gdname;
	}

	@Column(name = "GDBARCODE", length = 24)
	public String getGdbarcode() {
		return this.gdbarcode;
	}

	public void setGdbarcode(String gdbarcode) {
		this.gdbarcode = gdbarcode;
	}

	@Column(name = "GDCATID", length = 16)
	public String getGdcatid() {
		return this.gdcatid;
	}

	public void setGdcatid(String gdcatid) {
		this.gdcatid = gdcatid;
	}

	@Column(name = "GDCATNAME", length = 80)
	public String getGdcatname() {
		return this.gdcatname;
	}

	public void setGdcatname(String gdcatname) {
		this.gdcatname = gdcatname;
	}

	@Column(name = "GDPPNAME", length = 32)
	public String getGdppname() {
		return this.gdppname;
	}

	public void setGdppname(String gdppname) {
		this.gdppname = gdppname;
	}

	@Column(name = "GDSPEC", length = 32)
	public String getGdspec() {
		return this.gdspec;
	}

	public void setGdspec(String gdspec) {
		this.gdspec = gdspec;
	}

	@Column(name = "GDTAX", precision = 16)
	public BigDecimal getGdtax() {
		return this.gdtax;
	}

	public void setGdtax(BigDecimal gdtax) {
		this.gdtax = gdtax;
	}

	@Column(name = "GDAREA", length = 300)
	public String getGdarea() {
		return this.gdarea;
	}

	public void setGdarea(String gdarea) {
		this.gdarea = gdarea;
	}

	@Column(name = "GDUNIT", length = 16)
	public String getGdunit() {
		return this.gdunit;
	}

	public void setGdunit(String gdunit) {
		this.gdunit = gdunit;
	}

	@Column(name = "GDCSHH", length = 16)
	public String getGdcshh() {
		return this.gdcshh;
	}

	public void setGdcshh(String gdcshh) {
		this.gdcshh = gdcshh;
	}

	@Column(name = "TEMP1", length = 30)
	public String getTemp1() {
		return this.temp1;
	}

	public void setTemp1(String temp1) {
		this.temp1 = temp1;
	}

	@Column(name = "TEMP2", length = 30)
	public String getTemp2() {
		return this.temp2;
	}

	public void setTemp2(String temp2) {
		this.temp2 = temp2;
	}

	@Column(name = "TEMP3", length = 30)
	public String getTemp3() {
		return this.temp3;
	}

	public void setTemp3(String temp3) {
		this.temp3 = temp3;
	}

	@Column(name = "TEMP4", length = 30)
	public String getTemp4() {
		return this.temp4;
	}

	public void setTemp4(String temp4) {
		this.temp4 = temp4;
	}

	@Column(name = "TEMP5", length = 30)
	public String getTemp5() {
		return this.temp5;
	}

	public void setTemp5(String temp5) {
		this.temp5 = temp5;
	}

	@Column(name = "GDGXTIME")
	public Serializable getGdgxtime() {
		return this.gdgxtime;
	}

	public void setGdgxtime(Serializable gdgxtime) {
		this.gdgxtime = gdgxtime;
	}

	@Column(name = "GDFILE", length = 64)
	public String getGdfile() {
		return this.gdfile;
	}

	public void setGdfile(String gdfile) {
		this.gdfile = gdfile;
	}


	@Override
	public boolean equals(Object o) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public int hashCode() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return null;
	}


	@Transient
	public String getGdsgcode() {
		return gdsgcode;
	}

	public void setGdsgcode(String gdsgcode) {
		this.gdsgcode = gdsgcode;
	}

	@Transient
	public String getGdid() {
		return gdid;
	}

	public void setGdid(String gdid) {
		this.gdid = gdid;
	}

}
