package com.bfuture.app.saas.model;

// Generated 2011-12-7 14:38:38 by Hibernate Tools 3.2.2.GA

import java.io.Serializable;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InfGoodsuply generated by hbm2java
 */
@Entity
@Table(name = "INF_GOODSUPLY")
public class InfGoodsuply implements java.io.Serializable {

	private InfGoodsuplyId id;
	private String temp1;
	private String temp2;
	private String temp3;
	private String temp4;
	private String temp5;
	private Serializable gsgxtime;
	private String gsfile;

	public InfGoodsuply() {
	}

	public InfGoodsuply(InfGoodsuplyId id) {
		this.id = id;
	}

	public InfGoodsuply(InfGoodsuplyId id, String temp1, String temp2,
			String temp3, String temp4, String temp5, Serializable gsgxtime,
			String gsfile) {
		this.id = id;
		this.temp1 = temp1;
		this.temp2 = temp2;
		this.temp3 = temp3;
		this.temp4 = temp4;
		this.temp5 = temp5;
		this.gsgxtime = gsgxtime;
		this.gsfile = gsfile;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "gssgcode", column = @Column(name = "GSSGCODE", nullable = false, length = 30)),
			@AttributeOverride(name = "gsid", column = @Column(name = "GSID", nullable = false, length = 24)),
			@AttributeOverride(name = "gssupid", column = @Column(name = "GSSUPID", nullable = false, length = 30)),
			@AttributeOverride(name = "gsmfid", column = @Column(name = "GSMFID", nullable = false, length = 30)) })
	public InfGoodsuplyId getId() {
		return this.id;
	}

	public void setId(InfGoodsuplyId id) {
		this.id = id;
	}

	@Column(name = "TEMP1", length = 30)
	public String getTemp1() {
		return this.temp1;
	}

	public void setTemp1(String temp1) {
		this.temp1 = temp1;
	}

	@Column(name = "TEMP2", length = 30)
	public String getTemp2() {
		return this.temp2;
	}

	public void setTemp2(String temp2) {
		this.temp2 = temp2;
	}

	@Column(name = "TEMP3", length = 30)
	public String getTemp3() {
		return this.temp3;
	}

	public void setTemp3(String temp3) {
		this.temp3 = temp3;
	}

	@Column(name = "TEMP4", length = 30)
	public String getTemp4() {
		return this.temp4;
	}

	public void setTemp4(String temp4) {
		this.temp4 = temp4;
	}

	@Column(name = "TEMP5", length = 30)
	public String getTemp5() {
		return this.temp5;
	}

	public void setTemp5(String temp5) {
		this.temp5 = temp5;
	}

	@Column(name = "GSGXTIME")
	public Serializable getGsgxtime() {
		return this.gsgxtime;
	}

	public void setGsgxtime(Serializable gsgxtime) {
		this.gsgxtime = gsgxtime;
	}

	@Column(name = "GSFILE", length = 64)
	public String getGsfile() {
		return this.gsfile;
	}

	public void setGsfile(String gsfile) {
		this.gsfile = gsfile;
	}

}
