package com.bfuture.app.saas.model;

// Generated 2011-12-7 14:38:38 by Hibernate Tools 3.2.2.GA

import java.io.Serializable;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InfShop generated by hbm2java
 */
@Entity
@Table(name = "INF_SHOP")
public class InfShop implements java.io.Serializable {

	private InfShopId id;
	private String shpname;
	private String temp1;
	private String temp2;
	private String temp3;
	private String temp4;
	private String temp5;
	private Serializable crttime;
	private String shfile;

	public InfShop() {
	}

	public InfShop(InfShopId id) {
		this.id = id;
	}

	public InfShop(InfShopId id, String shpname, String temp1, String temp2,
			String temp3, String temp4, String temp5, Serializable crttime,
			String shfile) {
		this.id = id;
		this.shpname = shpname;
		this.temp1 = temp1;
		this.temp2 = temp2;
		this.temp3 = temp3;
		this.temp4 = temp4;
		this.temp5 = temp5;
		this.crttime = crttime;
		this.shfile = shfile;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "sgcode", column = @Column(name = "SGCODE", nullable = false, length = 30)),
			@AttributeOverride(name = "shpcode", column = @Column(name = "SHPCODE", nullable = false, length = 30)) })
	public InfShopId getId() {
		return this.id;
	}

	public void setId(InfShopId id) {
		this.id = id;
	}

	@Column(name = "SHPNAME", length = 80)
	public String getShpname() {
		return this.shpname;
	}

	public void setShpname(String shpname) {
		this.shpname = shpname;
	}

	@Column(name = "TEMP1", length = 16)
	public String getTemp1() {
		return this.temp1;
	}

	public void setTemp1(String temp1) {
		this.temp1 = temp1;
	}

	@Column(name = "TEMP2", length = 16)
	public String getTemp2() {
		return this.temp2;
	}

	public void setTemp2(String temp2) {
		this.temp2 = temp2;
	}

	@Column(name = "TEMP3", length = 16)
	public String getTemp3() {
		return this.temp3;
	}

	public void setTemp3(String temp3) {
		this.temp3 = temp3;
	}

	@Column(name = "TEMP4", length = 16)
	public String getTemp4() {
		return this.temp4;
	}

	public void setTemp4(String temp4) {
		this.temp4 = temp4;
	}

	@Column(name = "TEMP5", length = 16)
	public String getTemp5() {
		return this.temp5;
	}

	public void setTemp5(String temp5) {
		this.temp5 = temp5;
	}

	@Column(name = "CRTTIME")
	public Serializable getCrttime() {
		return this.crttime;
	}

	public void setCrttime(Serializable crttime) {
		this.crttime = crttime;
	}

	@Column(name = "SHFILE", length = 64)
	public String getShfile() {
		return this.shfile;
	}

	public void setShfile(String shfile) {
		this.shfile = shfile;
	}

}
