package com.bfuture.app.saas.model;

// Generated 2011-12-7 14:38:38 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InfShopId generated by hbm2java
 */
@Embeddable
public class InfShopId implements java.io.Serializable {

	private String sgcode;
	private String shpcode;

	public InfShopId() {
	}

	public InfShopId(String sgcode, String shpcode) {
		this.sgcode = sgcode;
		this.shpcode = shpcode;
	}

	@Column(name = "SGCODE", nullable = false, length = 30)
	public String getSgcode() {
		return this.sgcode;
	}

	public void setSgcode(String sgcode) {
		this.sgcode = sgcode;
	}

	@Column(name = "SHPCODE", nullable = false, length = 30)
	public String getShpcode() {
		return this.shpcode;
	}

	public void setShpcode(String shpcode) {
		this.shpcode = shpcode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InfShopId))
			return false;
		InfShopId castOther = (InfShopId) other;

		return ((this.getSgcode() == castOther.getSgcode()) || (this
				.getSgcode() != null
				&& castOther.getSgcode() != null && this.getSgcode().equals(
				castOther.getSgcode())))
				&& ((this.getShpcode() == castOther.getShpcode()) || (this
						.getShpcode() != null
						&& castOther.getShpcode() != null && this.getShpcode()
						.equals(castOther.getShpcode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSgcode() == null ? 0 : this.getSgcode().hashCode());
		result = 37 * result
				+ (getShpcode() == null ? 0 : this.getShpcode().hashCode());
		return result;
	}

}
