package com.bfuture.app.saas.model;

// Generated 2011-3-3 14:49:18 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InfSupinfoId generated by hbm2java
 */
@Embeddable
public class InfSupinfoId implements java.io.Serializable {

	private String supsgcode;
	private String supid;
	private String supmfid;

	public InfSupinfoId() {
	}

	public InfSupinfoId(String supsgcode, String supid, String supmfid) {
		this.supsgcode = supsgcode;
		this.supid = supid;
		this.supmfid = supmfid;
	}

	@Column(name = "SUPSGCODE", nullable = false, length = 30)
	public String getSupsgcode() {
		return this.supsgcode;
	}

	public void setSupsgcode(String supsgcode) {
		this.supsgcode = supsgcode;
	}

	@Column(name = "SUPID", nullable = false, length = 24)
	public String getSupid() {
		return this.supid;
	}

	public void setSupid(String supid) {
		this.supid = supid;
	}

	@Column(name = "SUPMFID", nullable = false, length = 30)
	public String getSupmfid() {
		return this.supmfid;
	}

	public void setSupmfid(String supmfid) {
		this.supmfid = supmfid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InfSupinfoId))
			return false;
		InfSupinfoId castOther = (InfSupinfoId) other;

		return ((this.getSupsgcode() == castOther.getSupsgcode()) || (this
				.getSupsgcode() != null
				&& castOther.getSupsgcode() != null && this.getSupsgcode()
				.equals(castOther.getSupsgcode())))
				&& ((this.getSupid() == castOther.getSupid()) || (this
						.getSupid() != null
						&& castOther.getSupid() != null && this.getSupid()
						.equals(castOther.getSupid())))
				&& ((this.getSupmfid() == castOther.getSupmfid()) || (this
						.getSupmfid() != null
						&& castOther.getSupmfid() != null && this.getSupmfid()
						.equals(castOther.getSupmfid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSupsgcode() == null ? 0 : this.getSupsgcode().hashCode());
		result = 37 * result
				+ (getSupid() == null ? 0 : this.getSupid().hashCode());
		result = 37 * result
				+ (getSupmfid() == null ? 0 : this.getSupmfid().hashCode());
		return result;
	}

}
