package com.bfuture.app.saas.model;

// Generated 2011-12-7 14:38:38 by Hibernate Tools 3.2.2.GA

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.hibernate.annotations.TypeDefs;
import org.springframework.orm.hibernate3.support.BlobByteArrayType;
import org.springframework.orm.hibernate3.support.ClobStringType;

import com.bfuture.app.basic.model.BaseObject;

/**
 * MsgMessage generated by hbm2java
 */
@Entity
@Table(name = "MSG_MESSAGE")
@TypeDefs({@TypeDef(name="clob",typeClass=ClobStringType.class),
@TypeDef(name="blob",typeClass=BlobByteArrayType.class)})
public class MsgMessage extends BaseObject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3892074275391162910L;
	
	private Long id;
	private String insC;
	private String mmTitle;
	private String mmEntType;
	private String mmReByC;
	private String enabledDx;
	private String enabledMail;
	private Date mmFbDate;
	private String mmContent;
	private String mmSendC;
	private String mmSendCn;
	private String crtByC;
	private Date crtByTime;
	private String lastUpByC;
	private Date lastUpByTime;
	private String mmMemo;
	private String mmStatus;
	private String temp1;
	private String temp2;
	private String temp3;
	private String temp4;
	private String temp5;
	
	private String viewFlag;

	public MsgMessage() {
	}

	public MsgMessage(Long id, String insC, String mmTitle, String mmReByC) {
		this.id = id;
		this.insC = insC;
		this.mmTitle = mmTitle;
		this.mmReByC = mmReByC;
	}

	public MsgMessage(Long id, String insC, String mmTitle,
			String mmEntType, String mmReByC, String enabledDx,
			String enabledMail, Date mmFbDate, String mmContent,
			String mmSendC, String crtByC, Date crtByTime,
			String lastUpByC, Date lastUpByTime, String mmMemo,
			String mmStatus, String temp1, String temp2, String temp3,
			String temp4, String temp5) {
		this.id = id;
		this.insC = insC;
		this.mmTitle = mmTitle;
		this.mmEntType = mmEntType;
		this.mmReByC = mmReByC;
		this.enabledDx = enabledDx;
		this.enabledMail = enabledMail;
		this.mmFbDate = mmFbDate;
		this.mmContent = mmContent;
		this.mmSendC = mmSendC;
		this.crtByC = crtByC;
		this.crtByTime = crtByTime;
		this.lastUpByC = lastUpByC;
		this.lastUpByTime = lastUpByTime;
		this.mmMemo = mmMemo;
		this.mmStatus = mmStatus;
		this.temp1 = temp1;
		this.temp2 = temp2;
		this.temp3 = temp3;
		this.temp4 = temp4;
		this.temp5 = temp5;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_MESSAGE")
	@SequenceGenerator(name = "SEQ_MESSAGE", sequenceName = "SEQ_MSG_MESSAGE", allocationSize = 1)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "INS_C", nullable = false, length = 30)
	public String getInsC() {
		return this.insC;
	}

	public void setInsC(String insC) {
		this.insC = insC;
	}

	@Column(name = "MM_TITLE", nullable = false, length = 500)
	public String getMmTitle() {
		return this.mmTitle;
	}

	public void setMmTitle(String mmTitle) {
		this.mmTitle = mmTitle;
	}

	@Column(name = "MM_ENT_TYPE", length = 30)
	public String getMmEntType() {
		return this.mmEntType;
	}

	public void setMmEntType(String mmEntType) {
		this.mmEntType = mmEntType;
	}

	@Column(name = "MM_RE_BY_C", nullable = false, length = 30)
	public String getMmReByC() {
		return this.mmReByC;
	}

	public void setMmReByC(String mmReByC) {
		this.mmReByC = mmReByC;
	}

	@Column(name = "ENABLED_DX", length = 1)
	public String getEnabledDx() {
		return this.enabledDx;
	}

	public void setEnabledDx(String enabledDx) {
		this.enabledDx = enabledDx;
	}

	@Column(name = "ENABLED_MAIL", length = 1)
	public String getEnabledMail() {
		return this.enabledMail;
	}

	public void setEnabledMail(String enabledMail) {
		this.enabledMail = enabledMail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MM_FB_DATE")
	public Date getMmFbDate() {
		return this.mmFbDate;
	}

	public void setMmFbDate(Date mmFbDate) {
		this.mmFbDate = mmFbDate;
	}

	@Lob
	@Type(type="clob")
	@Column(name = "MM_CONTENT")
	public String getMmContent() {
		return this.mmContent;
	}

	public void setMmContent(String mmContent) {
		this.mmContent = mmContent;
	}

	@Column(name = "MM_SEND_C", length = 30)
	public String getMmSendC() {
		return this.mmSendC;
	}

	public void setMmSendC(String mmSendC) {
		this.mmSendC = mmSendC;
	}
	
	@Column(name = "MM_SEND_CN")
	public String getMmSendCn() {
		return mmSendCn;
	}

	public void setMmSendCn(String mmSendCn) {
		this.mmSendCn = mmSendCn;
	}

	@Column(name = "CRT_BY_C", length = 30)
	public String getCrtByC() {
		return this.crtByC;
	}

	public void setCrtByC(String crtByC) {
		this.crtByC = crtByC;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRT_BY_TIME")
	public Date getCrtByTime() {
		return this.crtByTime;
	}

	public void setCrtByTime(Date crtByTime) {
		this.crtByTime = crtByTime;
	}

	@Column(name = "LAST_UP_BY_C", length = 30)
	public String getLastUpByC() {
		return this.lastUpByC;
	}

	public void setLastUpByC(String lastUpByC) {
		this.lastUpByC = lastUpByC;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UP_BY_TIME")
	public Date getLastUpByTime() {
		return this.lastUpByTime;
	}

	public void setLastUpByTime(Date lastUpByTime) {
		this.lastUpByTime = lastUpByTime;
	}

	@Column(name = "MM_MEMO", length = 100)
	public String getMmMemo() {
		return this.mmMemo;
	}

	public void setMmMemo(String mmMemo) {
		this.mmMemo = mmMemo;
	}

	@Column(name = "MM_STATUS", length = 30)
	public String getMmStatus() {
		return this.mmStatus;
	}

	public void setMmStatus(String mmStatus) {
		this.mmStatus = mmStatus;
	}

	@Column(name = "TEMP1", length = 30)
	public String getTemp1() {
		return this.temp1;
	}

	public void setTemp1(String temp1) {
		this.temp1 = temp1;
	}

	@Column(name = "TEMP2", length = 30)
	public String getTemp2() {
		return this.temp2;
	}

	public void setTemp2(String temp2) {
		this.temp2 = temp2;
	}

	@Column(name = "TEMP3", length = 30)
	public String getTemp3() {
		return this.temp3;
	}

	public void setTemp3(String temp3) {
		this.temp3 = temp3;
	}

	@Column(name = "TEMP4", length = 30)
	public String getTemp4() {
		return this.temp4;
	}

	public void setTemp4(String temp4) {
		this.temp4 = temp4;
	}

	@Column(name = "TEMP5", length = 30)
	public String getTemp5() {
		return this.temp5;
	}

	public void setTemp5(String temp5) {
		this.temp5 = temp5;
	}

	@Transient	
	public String getViewFlag() {
		return viewFlag;
	}

	public void setViewFlag(String viewFlag) {
		this.viewFlag = viewFlag;
	}

	@Override
	public boolean equals(Object o) {		
		return false;
	}

	@Override
	public int hashCode() {
		return 0;
	}

	@Override
	public String toString() {
		return null;
	}

}
