package com.bfuture.app.saas.model;

// Generated 2011-12-7 14:38:38 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.hibernate.annotations.TypeDefs;
import org.springframework.orm.hibernate3.support.BlobByteArrayType;
import org.springframework.orm.hibernate3.support.ClobStringType;

import com.bfuture.app.basic.model.BaseObject;
import com.bfuture.app.saas.util.DateUtil;

/**
 * MsgNotice generated by hbm2java
 */
@Entity
@Table(name = "MSG_NOTICE")
@TypeDefs({@TypeDef(name="clob",typeClass=ClobStringType.class),
@TypeDef(name="blob",typeClass=BlobByteArrayType.class)})
public class MsgNotice extends BaseObject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3061980404129546874L;
	private Integer id;
	private String insC;
	private String mnTitle;
	private String mnContent;
	private String mnEntType;
	private Date mnFbDate;
	private String enabled;
	private Date mnBeginDate;
	private Date mnEndDate;
	private String crtByC;
	private String crtByCn;
	private Date crtByTime;
	private String lastUpByC;
	private Date lastUpByTime;
	private String mnMemo;
	private String mnStatus;
	private String temp1;
	private String temp2;
	private String temp3;
	private String temp4;
	private String temp5;
	
	private String startDate;
	private String endDate;

	public MsgNotice() {
	}

	public MsgNotice(Integer id, String insC, String mnTitle) {
		this.id = id;
		this.insC = insC;
		this.mnTitle = mnTitle;
	}

	public MsgNotice(Integer id, String insC, String mnTitle,
			String mnContent, String mnEntType, Date mnFbDate,
			String enabled, Date mnBeginDate, Date mnEndDate,
			String crtByC, Date crtByTime, String lastUpByC,
			Date lastUpByTime, String mnMemo, String mnStatus,
			String temp1, String temp2, String temp3, String temp4, String temp5) {
		this.id = id;
		this.insC = insC;
		this.mnTitle = mnTitle;
		this.mnContent = mnContent;
		this.mnEntType = mnEntType;
		this.mnFbDate = mnFbDate;
		this.enabled = enabled;
		this.mnBeginDate = mnBeginDate;
		this.mnEndDate = mnEndDate;
		this.crtByC = crtByC;
		this.crtByTime = crtByTime;
		this.lastUpByC = lastUpByC;
		this.lastUpByTime = lastUpByTime;
		this.mnMemo = mnMemo;
		this.mnStatus = mnStatus;
		this.temp1 = temp1;
		this.temp2 = temp2;
		this.temp3 = temp3;
		this.temp4 = temp4;
		this.temp5 = temp5;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_NOTICE")
	@SequenceGenerator(name = "SEQ_NOTICE", sequenceName = "SEQ_MSG_NOTICE", allocationSize = 1)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "INS_C", nullable = false, length = 30)
	public String getInsC() {
		return this.insC;
	}

	public void setInsC(String insC) {
		this.insC = insC;
	}

	@Column(name = "MN_TITLE", nullable = false, length = 500)
	public String getMnTitle() {
		return this.mnTitle;
	}

	public void setMnTitle(String mnTitle) {
		this.mnTitle = mnTitle;
	}

	@Lob
	@Type(type="clob")
	@Column(name = "MN_CONTENT")
	public String getMnContent() {
		return this.mnContent;
	}

	public void setMnContent(String mnContent) {
		this.mnContent = mnContent;
	}

	@Column(name = "MN_ENT_TYPE", length = 30)
	public String getMnEntType() {
		return this.mnEntType;
	}

	public void setMnEntType(String mnEntType) {
		this.mnEntType = mnEntType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MN_FB_DATE")
	public Date getMnFbDate() {
		return this.mnFbDate;
	}

	public void setMnFbDate(Date mnFbDate) {
		this.mnFbDate = mnFbDate;
	}

	@Column(name = "ENABLED", length = 1)
	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MN_BEGIN_DATE")
	public Date getMnBeginDate() {
		return this.mnBeginDate;
	}

	public void setMnBeginDate(Date mnBeginDate) {
		this.mnBeginDate = mnBeginDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MN_END_DATE")
	public Date getMnEndDate() {
		return this.mnEndDate;
	}

	public void setMnEndDate(Date mnEndDate) {
		this.mnEndDate = mnEndDate;
	}

	@Column(name = "CRT_BY_C", length = 30)
	public String getCrtByC() {
		return this.crtByC;
	}

	public void setCrtByC(String crtByC) {
		this.crtByC = crtByC;
	}
	
	@Column(name = "CRT_BY_CN")
	public String getCrtByCn() {
		return crtByCn;
	}

	public void setCrtByCn(String crtByCn) {
		this.crtByCn = crtByCn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRT_BY_TIME")
	public Date getCrtByTime() {
		return this.crtByTime;
	}

	public void setCrtByTime(Date crtByTime) {
		this.crtByTime = crtByTime;
	}

	@Column(name = "LAST_UP_BY_C", length = 30)
	public String getLastUpByC() {
		return this.lastUpByC;
	}

	public void setLastUpByC(String lastUpByC) {
		this.lastUpByC = lastUpByC;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UP_BY_TIME")
	public Date getLastUpByTime() {
		return this.lastUpByTime;
	}

	public void setLastUpByTime(Date lastUpByTime) {
		this.lastUpByTime = lastUpByTime;
	}

	@Column(name = "MN_MEMO", length = 30)
	public String getMnMemo() {
		return this.mnMemo;
	}

	public void setMnMemo(String mnMemo) {
		this.mnMemo = mnMemo;
	}

	@Column(name = "MN_STATUS", length = 30)
	public String getMnStatus() {
		return this.mnStatus;
	}

	public void setMnStatus(String mnStatus) {
		this.mnStatus = mnStatus;
	}

	@Column(name = "TEMP1", length = 30)
	public String getTemp1() {
		return this.temp1;
	}

	public void setTemp1(String temp1) {
		this.temp1 = temp1;
	}

	@Column(name = "TEMP2", length = 30)
	public String getTemp2() {
		return this.temp2;
	}

	public void setTemp2(String temp2) {
		this.temp2 = temp2;
	}

	@Column(name = "TEMP3", length = 30)
	public String getTemp3() {
		return this.temp3;
	}

	public void setTemp3(String temp3) {
		this.temp3 = temp3;
	}

	@Column(name = "TEMP4", length = 30)
	public String getTemp4() {
		return this.temp4;
	}

	public void setTemp4(String temp4) {
		this.temp4 = temp4;
	}

	@Column(name = "TEMP5", length = 30)
	public String getTemp5() {
		return this.temp5;
	}

	public void setTemp5(String temp5) {
		this.temp5 = temp5;
	}

	@Override
	public boolean equals(Object o) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public int hashCode() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return null;
	}

	@Transient
	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
		this.mnBeginDate = DateUtil.convertDate( startDate );
	}

	@Transient
	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
		this.mnEndDate = DateUtil.convertDate( endDate );
	}

}
