package com.bfuture.app.saas.model;

// Generated 2011-3-8 7:44:48 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.bfuture.app.basic.model.BaseObject;

/**
 * SysLogevent generated by hbm2java
 */
@Entity
@Table(name = "SYS_LOGEVENT")
public class SysLogevent extends BaseObject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6148120709844221921L;
	private Integer id;
	private String sgcode;
	private String sucode;
	private String supcode;
	private Date letime;
	private String letype;
	private String lecontent;
	private String temp1;
	private String temp2;
	private String temp3;
	private String temp4;
	private String temp5;
	private String bdate;
	private String edate;

	public SysLogevent() {
	}

	public SysLogevent(Integer id, String sgcode, String sucode, Date letime) {
		this.id = id;
		this.sgcode = sgcode;
		this.sucode = sucode;
		this.letime = letime;
	}

	public SysLogevent(Integer id, String sgcode, String sucode,
			String supcode, Date letime, String letype, String lecontent) {
		this.id = id;
		this.sgcode = sgcode;
		this.sucode = sucode;
		this.supcode = supcode;
		this.letime = letime;
		this.letype = letype;
		this.lecontent = lecontent;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_LOGEVENT")
	@SequenceGenerator(name = "SEQ_LOGEVENT", sequenceName = "SEQ_SYS_LOGEVENT", allocationSize = 1)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "SGCODE", nullable = false, length = 30)
	public String getSgcode() {
		return this.sgcode;
	}

	public void setSgcode(String sgcode) {
		this.sgcode = sgcode;
	}

	@Column(name = "SUCODE", nullable = false, length = 30)
	public String getSucode() {
		return this.sucode;
	}

	public void setSucode(String sucode) {
		this.sucode = sucode;
	}

	@Column(name = "SUPCODE", length = 30)
	public String getSupcode() {
		return this.supcode;
	}

	public void setSupcode(String supcode) {
		this.supcode = supcode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LETIME", nullable = false, length = 26)
	public Date getLetime() {
		return this.letime;
	}

	public void setLetime(Date letime) {
		this.letime = letime;
	}

	@Column(name = "LETYPE", length = 30)
	public String getLetype() {
		return this.letype;
	}

	public void setLetype(String letype) {
		this.letype = letype;
	}

	@Column(name = "LECONTENT", length = 200)
	public String getLecontent() {
		return this.lecontent;
	}

	public void setLecontent(String lecontent) {
		this.lecontent = lecontent;
	}

	@Column(name = "TEMP1", length = 30)
	public String getTemp1() {
		return this.temp1;
	}

	public void setTemp1(String temp1) {
		this.temp1 = temp1;
	}

	@Column(name = "TEMP2", length = 30)
	public String getTemp2() {
		return this.temp2;
	}

	public void setTemp2(String temp2) {
		this.temp2 = temp2;
	}

	@Column(name = "TEMP3", length = 30)
	public String getTemp3() {
		return this.temp3;
	}

	public void setTemp3(String temp3) {
		this.temp3 = temp3;
	}

	@Column(name = "TEMP4", length = 30)
	public String getTemp4() {
		return this.temp4;
	}

	public void setTemp4(String temp4) {
		this.temp4 = temp4;
	}

	@Column(name = "TEMP5", length = 30)
	public String getTemp5() {
		return this.temp5;
	}

	public void setTemp5(String temp5) {
		this.temp5 = temp5;
	}

	@Override
	public boolean equals(Object o) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public int hashCode() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return null;
	}

	@Transient
	public String getBdate() {
		return bdate;
	}

	public void setBdate(String bdate) {
		this.bdate = bdate;
	}

	@Transient
	public String getEdate() {
		return edate;
	}

	public void setEdate(String edate) {
		this.edate = edate;
	}

}
