package com.bfuture.app.saas.model;

// Generated 2011-3-8 10:36:54 by Hibernate Tools 3.2.2.GA

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.bfuture.app.basic.model.BaseObject;

/**
 * SysMenu generated by hbm2java
 */
@Entity
@Table(name = "SYS_MENU")
public class SysMenu extends BaseObject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9029063812992312106L;
	private String meucode;
	private String meuname;
	private String meupcode;
	private Integer meulevel;
	private String meumemo;
	private String meuleaf;
	private String meuenable;
	private String meuhref;
	private String relationC;
	private String fullscreen;
	private String icon;
	private String id;	
	private String text;
	private String state;
	private String checked;
	private String temp1;
	private String temp2;
	private String temp3;
	private String temp4;
	private String temp5;
	
	private List<SysMenu> children;

	public SysMenu(){
	}

	public SysMenu(String meucode) {
		this.meucode = meucode;
	}

	public SysMenu(String meucode, String meuname, String meupcode,
			Integer meulevel, String meumemo, String meuleaf,
			String meuenable, String meuhref, String relationC,
			String temp1, String temp2, String temp3, String temp4, String temp5) {
		this.meucode = meucode;
		this.meuname = meuname;
		this.meupcode = meupcode;
		this.meulevel = meulevel;
		this.meumemo = meumemo;
		this.meuleaf = meuleaf;
		this.meuenable = meuenable;
		this.meuhref = meuhref;
		this.relationC = relationC;
		this.temp1 = temp1;
		this.temp2 = temp2;
		this.temp3 = temp3;
		this.temp4 = temp4;
		this.temp5 = temp5;
	}

	@Id
	@Column(name = "MEUCODE", unique = true, nullable = false, length = 36)
	public String getMeucode() {
		return this.meucode;
	}

	public void setMeucode(String meucode) {
		this.meucode = meucode;
	}

	@Column(name = "MEUNAME", length = 128)
	public String getMeuname() {
		return this.meuname;
	}

	public void setMeuname(String meuname) {
		this.meuname = meuname;
	}

	@Column(name = "MEUPCODE", length = 36)
	public String getMeupcode() {
		return this.meupcode;
	}

	public void setMeupcode(String meupcode) {
		this.meupcode = meupcode;
	}

	@Column(name = "MEULEVEL")
	public Integer getMeulevel() {
		return this.meulevel;
	}

	public void setMeulevel(Integer meulevel) {
		this.meulevel = meulevel;
	}

	@Column(name = "MEUMEMO", length = 250)
	public String getMeumemo() {
		return this.meumemo;
	}

	public void setMeumemo(String meumemo) {
		this.meumemo = meumemo;
	}

	@Column(name = "MEULEAF", length = 1)
	public String getMeuleaf() {
		return this.meuleaf;
	}

	public void setMeuleaf(String meuleaf) {
		this.meuleaf = meuleaf;
	}

	@Column(name = "MEUENABLE", length = 1)
	public String getMeuenable() {
		return this.meuenable;
	}

	public void setMeuenable(String meuenable) {
		this.meuenable = meuenable;
	}

	@Column(name = "MEUHREF", length = 128)
	public String getMeuhref() {
		return this.meuhref;
	}

	public void setMeuhref(String meuhref) {
		this.meuhref = meuhref;
	}

	@Column(name = "RELATION_C", length = 36)
	public String getRelationC() {
		return this.relationC;
	}

	public void setRelationC(String relationC) {
		this.relationC = relationC;
	}
	
	@Transient
	public String getIconCls() {
		return icon;
	}

	public void setIconCls(String icon) {
		this.icon = icon;
	}

	@Column(name = "ICON", length = 50)
	public String getIcon() {
		return icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "FULLSCREEN", length = 1)
	public String getFullscreen() {
		return fullscreen;
	}

	public void setFullscreen(String fullscreen) {
		this.fullscreen = fullscreen;
	}

	@Column(name = "TEMP1", length = 30)
	public String getTemp1() {
		return this.temp1;
	}

	public void setTemp1(String temp1) {
		this.temp1 = temp1;
	}

	@Column(name = "TEMP2", length = 30)
	public String getTemp2() {
		return this.temp2;
	}

	public void setTemp2(String temp2) {
		this.temp2 = temp2;
	}

	@Column(name = "TEMP3", length = 30)
	public String getTemp3() {
		return this.temp3;
	}

	public void setTemp3(String temp3) {
		this.temp3 = temp3;
	}

	@Column(name = "TEMP4", length = 30)
	public String getTemp4() {
		return this.temp4;
	}

	public void setTemp4(String temp4) {
		this.temp4 = temp4;
	}

	@Column(name = "TEMP5", length = 30)
	public String getTemp5() {
		return this.temp5;
	}

	public void setTemp5(String temp5) {
		this.temp5 = temp5;
	}

	@Transient
	public String getId() {
		return id != null ? id : meucode;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Transient
	public String getText() {
		return text != null ? id : meuname;
	}

	public void setText(String text) {
		this.text = text;
	}
	
	@Transient
	public String getChecked() {
		return checked;
	}

	public void setChecked(String checked) {
		this.checked = checked;
	}
	
	@Transient
	public String getState() {
		return "Y".equals( meuleaf ) ? "open" : "closed";
	}

	public void setState(String state) {
		this.state = state;
	}

	@Transient
	public List<SysMenu> getChildren() {
		return children;
	}

	public void setChildren(List<SysMenu> children) {
		this.children = children;
	}

	@Override
	public boolean equals(Object o) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public int hashCode() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return null;
	}
}
