package com.bfuture.app.saas.model;

// Generated 2011-3-3 7:40:51 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.bfuture.app.basic.model.BaseObject;

/**
 * SysRole generated by hbm2java
 */
@Entity
@Table(name = "SYS_ROLE")
public class SysRole extends BaseObject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 581726651967979441L;
	private String rlcode;
	private String rlname;
	private Character rltype;
	private Character rlflag;
	private String sgcode;

	public SysRole() {
	}

	public SysRole(String rlcode, String rlname) {
		this.rlcode = rlcode;
		this.rlname = rlname;
	}

	public SysRole(String rlcode, String rlname, Character rltype,
			Character rlflag, String sgcode) {
		this.rlcode = rlcode;
		this.rlname = rlname;
		this.rltype = rltype;
		this.rlflag = rlflag;
		this.sgcode = sgcode;
	}

	@Id
	@Column(name = "RLCODE", unique = true, nullable = false, length = 30)
	public String getRlcode() {
		return this.rlcode;
	}

	public void setRlcode(String rlcode) {
		this.rlcode = rlcode;
	}

	@Column(name = "RLNAME", nullable = false, length = 80)
	public String getRlname() {
		return this.rlname;
	}

	public void setRlname(String rlname) {
		this.rlname = rlname;
	}

	@Column(name = "RLTYPE", length = 1)
	public Character getRltype() {
		return this.rltype;
	}

	public void setRltype(Character rltype) {
		this.rltype = rltype;
	}

	@Column(name = "RLFLAG", length = 1)
	public Character getRlflag() {
		return this.rlflag;
	}

	public void setRlflag(Character rlflag) {
		this.rlflag = rlflag;
	}
	
	@Column(name = "SGCODE", length = 30)
	public String getSgcode() {
		return this.sgcode;
	}

	public void setSgcode(String sgcode) {
		this.sgcode = sgcode;
	}

	@Override
	public boolean equals(Object o) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public int hashCode() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return null;
	}

}
