package com.bfuture.app.saas.model;

// Generated 2011-3-17 7:22:25 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysRlmeuId generated by hbm2java
 */
@Embeddable
public class SysRlmeuId implements java.io.Serializable {

	private String rlcode;
	private String meucode;

	public SysRlmeuId() {
	}

	public SysRlmeuId(String rlcode, String meucode) {
		this.rlcode = rlcode;
		this.meucode = meucode;
	}

	@Column(name = "RLCODE", nullable = false, length = 30)
	public String getRlcode() {
		return this.rlcode;
	}

	public void setRlcode(String rlcode) {
		this.rlcode = rlcode;
	}

	@Column(name = "MEUCODE", nullable = false, length = 30)
	public String getMeucode() {
		return this.meucode;
	}

	public void setMeucode(String meucode) {
		this.meucode = meucode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SysRlmeuId))
			return false;
		SysRlmeuId castOther = (SysRlmeuId) other;

		return ((this.getRlcode() == castOther.getRlcode()) || (this
				.getRlcode() != null
				&& castOther.getRlcode() != null && this.getRlcode().equals(
				castOther.getRlcode())))
				&& ((this.getMeucode() == castOther.getMeucode()) || (this
						.getMeucode() != null
						&& castOther.getMeucode() != null && this.getMeucode()
						.equals(castOther.getMeucode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRlcode() == null ? 0 : this.getRlcode().hashCode());
		result = 37 * result
				+ (getMeucode() == null ? 0 : this.getMeucode().hashCode());
		return result;
	}

}
