package com.bfuture.app.saas.model;

// Generated 2011-12-7 14:38:38 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * YwBinstrheadId generated by hbm2java
 */
@Embeddable
public class YwBinstrheadId implements java.io.Serializable {

	private String bihsgcode;
	private String bihbillno;
	private String bihshmfid;

	public YwBinstrheadId() {
	}

	public YwBinstrheadId(String bihsgcode, String bihbillno, String bihshmfid) {
		this.bihsgcode = bihsgcode;
		this.bihbillno = bihbillno;
		this.bihshmfid = bihshmfid;
	}

	@Column(name = "BIHSGCODE", nullable = false, length = 30)
	public String getBihsgcode() {
		return this.bihsgcode;
	}

	public void setBihsgcode(String bihsgcode) {
		this.bihsgcode = bihsgcode;
	}

	@Column(name = "BIHBILLNO", nullable = false, length = 32)
	public String getBihbillno() {
		return this.bihbillno;
	}

	public void setBihbillno(String bihbillno) {
		this.bihbillno = bihbillno;
	}

	@Column(name = "BIHSHMFID", nullable = false, length = 30)
	public String getBihshmfid() {
		return this.bihshmfid;
	}

	public void setBihshmfid(String bihshmfid) {
		this.bihshmfid = bihshmfid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof YwBinstrheadId))
			return false;
		YwBinstrheadId castOther = (YwBinstrheadId) other;

		return ((this.getBihsgcode() == castOther.getBihsgcode()) || (this
				.getBihsgcode() != null
				&& castOther.getBihsgcode() != null && this.getBihsgcode()
				.equals(castOther.getBihsgcode())))
				&& ((this.getBihbillno() == castOther.getBihbillno()) || (this
						.getBihbillno() != null
						&& castOther.getBihbillno() != null && this
						.getBihbillno().equals(castOther.getBihbillno())))
				&& ((this.getBihshmfid() == castOther.getBihshmfid()) || (this
						.getBihshmfid() != null
						&& castOther.getBihshmfid() != null && this
						.getBihshmfid().equals(castOther.getBihshmfid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getBihsgcode() == null ? 0 : this.getBihsgcode().hashCode());
		result = 37 * result
				+ (getBihbillno() == null ? 0 : this.getBihbillno().hashCode());
		result = 37 * result
				+ (getBihshmfid() == null ? 0 : this.getBihshmfid().hashCode());
		return result;
	}

}
