package com.bfuture.app.saas.model;

// Generated 2011-12-7 14:38:38 by Hibernate Tools 3.2.2.GA

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * YwBinstrdetail generated by hbm2java
 * 入库单明细
 */
@Entity
@Table(name = "YW_BINSTRDETAIL")
public class YwBinstrdetail implements java.io.Serializable {

	private YwBinstrdetailId id;
	private BigDecimal bidsl;
	private BigDecimal bidtax;
	private BigDecimal bidhsjj;
	private BigDecimal bidhsjjje;
	private String temp1;
	private String temp2;
	private String temp3;
	private String temp4;
	private String temp5;
	private Serializable bidtime;
	private String bidfile;

	public YwBinstrdetail() {
	}

	public YwBinstrdetail(YwBinstrdetailId id) {
		this.id = id;
	}

	public YwBinstrdetail(YwBinstrdetailId id, BigDecimal bidsl,
			BigDecimal bidtax, BigDecimal bidhsjj, BigDecimal bidhsjjje,
			String temp1, String temp2, String temp3, String temp4,
			String temp5, Serializable bidtime, String bidfile) {
		this.id = id;
		this.bidsl = bidsl;
		this.bidtax = bidtax;
		this.bidhsjj = bidhsjj;
		this.bidhsjjje = bidhsjjje;
		this.temp1 = temp1;
		this.temp2 = temp2;
		this.temp3 = temp3;
		this.temp4 = temp4;
		this.temp5 = temp5;
		this.bidtime = bidtime;
		this.bidfile = bidfile;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "bidsgcode", column = @Column(name = "BIDSGCODE", nullable = false, length = 30)),
			@AttributeOverride(name = "bidgdid", column = @Column(name = "BIDGDID", nullable = false, length = 24)),
			@AttributeOverride(name = "bidbillno", column = @Column(name = "BIDBILLNO", nullable = false, length = 32)),
			@AttributeOverride(name = "bidshmfid", column = @Column(name = "BIDSHMFID", nullable = false, length = 30)) })
	public YwBinstrdetailId getId() {
		return this.id;
	}

	public void setId(YwBinstrdetailId id) {
		this.id = id;
	}

	@Column(name = "BIDSL", precision = 18, scale = 6)
	public BigDecimal getBidsl() {
		return this.bidsl;
	}

	public void setBidsl(BigDecimal bidsl) {
		this.bidsl = bidsl;
	}

	@Column(name = "BIDTAX", precision = 5)
	public BigDecimal getBidtax() {
		return this.bidtax;
	}

	public void setBidtax(BigDecimal bidtax) {
		this.bidtax = bidtax;
	}

	@Column(name = "BIDHSJJ", precision = 18, scale = 6)
	public BigDecimal getBidhsjj() {
		return this.bidhsjj;
	}

	public void setBidhsjj(BigDecimal bidhsjj) {
		this.bidhsjj = bidhsjj;
	}

	@Column(name = "BIDHSJJJE", precision = 18, scale = 6)
	public BigDecimal getBidhsjjje() {
		return this.bidhsjjje;
	}

	public void setBidhsjjje(BigDecimal bidhsjjje) {
		this.bidhsjjje = bidhsjjje;
	}

	@Column(name = "TEMP1", length = 30)
	public String getTemp1() {
		return this.temp1;
	}

	public void setTemp1(String temp1) {
		this.temp1 = temp1;
	}

	@Column(name = "TEMP2", length = 30)
	public String getTemp2() {
		return this.temp2;
	}

	public void setTemp2(String temp2) {
		this.temp2 = temp2;
	}

	@Column(name = "TEMP3", length = 30)
	public String getTemp3() {
		return this.temp3;
	}

	public void setTemp3(String temp3) {
		this.temp3 = temp3;
	}

	@Column(name = "TEMP4", length = 30)
	public String getTemp4() {
		return this.temp4;
	}

	public void setTemp4(String temp4) {
		this.temp4 = temp4;
	}

	@Column(name = "TEMP5", length = 30)
	public String getTemp5() {
		return this.temp5;
	}

	public void setTemp5(String temp5) {
		this.temp5 = temp5;
	}

	@Column(name = "BIDTIME")
	public Serializable getBidtime() {
		return this.bidtime;
	}

	public void setBidtime(Serializable bidtime) {
		this.bidtime = bidtime;
	}

	@Column(name = "BIDFILE", length = 64)
	public String getBidfile() {
		return this.bidfile;
	}

	public void setBidfile(String bidfile) {
		this.bidfile = bidfile;
	}

}
