package com.bfuture.app.saas.model;

// Generated 2011-12-7 14:38:38 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * YwBinstrdetailId generated by hbm2java
 */
@Embeddable
public class YwBinstrdetailId implements java.io.Serializable {

	private String bidsgcode;
	private String bidgdid;
	private String bidbillno;
	private String bidshmfid;

	public YwBinstrdetailId() {
	}

	public YwBinstrdetailId(String bidsgcode, String bidgdid, String bidbillno,
			String bidshmfid) {
		this.bidsgcode = bidsgcode;
		this.bidgdid = bidgdid;
		this.bidbillno = bidbillno;
		this.bidshmfid = bidshmfid;
	}

	@Column(name = "BIDSGCODE", nullable = false, length = 30)
	public String getBidsgcode() {
		return this.bidsgcode;
	}

	public void setBidsgcode(String bidsgcode) {
		this.bidsgcode = bidsgcode;
	}

	@Column(name = "BIDGDID", nullable = false, length = 24)
	public String getBidgdid() {
		return this.bidgdid;
	}

	public void setBidgdid(String bidgdid) {
		this.bidgdid = bidgdid;
	}

	@Column(name = "BIDBILLNO", nullable = false, length = 32)
	public String getBidbillno() {
		return this.bidbillno;
	}

	public void setBidbillno(String bidbillno) {
		this.bidbillno = bidbillno;
	}

	@Column(name = "BIDSHMFID", nullable = false, length = 30)
	public String getBidshmfid() {
		return this.bidshmfid;
	}

	public void setBidshmfid(String bidshmfid) {
		this.bidshmfid = bidshmfid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof YwBinstrdetailId))
			return false;
		YwBinstrdetailId castOther = (YwBinstrdetailId) other;

		return ((this.getBidsgcode() == castOther.getBidsgcode()) || (this
				.getBidsgcode() != null
				&& castOther.getBidsgcode() != null && this.getBidsgcode()
				.equals(castOther.getBidsgcode())))
				&& ((this.getBidgdid() == castOther.getBidgdid()) || (this
						.getBidgdid() != null
						&& castOther.getBidgdid() != null && this.getBidgdid()
						.equals(castOther.getBidgdid())))
				&& ((this.getBidbillno() == castOther.getBidbillno()) || (this
						.getBidbillno() != null
						&& castOther.getBidbillno() != null && this
						.getBidbillno().equals(castOther.getBidbillno())))
				&& ((this.getBidshmfid() == castOther.getBidshmfid()) || (this
						.getBidshmfid() != null
						&& castOther.getBidshmfid() != null && this
						.getBidshmfid().equals(castOther.getBidshmfid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getBidsgcode() == null ? 0 : this.getBidsgcode().hashCode());
		result = 37 * result
				+ (getBidgdid() == null ? 0 : this.getBidgdid().hashCode());
		result = 37 * result
				+ (getBidbillno() == null ? 0 : this.getBidbillno().hashCode());
		result = 37 * result
				+ (getBidshmfid() == null ? 0 : this.getBidshmfid().hashCode());
		return result;
	}

}
