package com.bfuture.app.saas.model;

// Generated 2011-12-7 14:38:38 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.bfuture.app.basic.model.BaseObject;

/**
 * YwBorderdetId generated by hbm2java
 */
@Embeddable
public class YwBorderdetId extends BaseObject implements java.io.Serializable {

	private String bodsgcode; // 实例编码
	private String bodbillno; // 订单编号
	private String bodshmfid; // 门店编号
	private String bodgdid;   // 商品编码

	public YwBorderdetId() {
	}

	public YwBorderdetId(String bodsgcode, String bodbillno, String bodshmfid,
			String bodgdid) {
		this.bodsgcode = bodsgcode;
		this.bodbillno = bodbillno;
		this.bodshmfid = bodshmfid;
		this.bodgdid = bodgdid;
	}

	@Column(name = "BODSGCODE", nullable = false, length = 30)
	public String getBodsgcode() {
		return this.bodsgcode;
	}

	public void setBodsgcode(String bodsgcode) {
		this.bodsgcode = bodsgcode;
	}

	@Column(name = "BODBILLNO", nullable = false, length = 32)
	public String getBodbillno() {
		return this.bodbillno;
	}

	public void setBodbillno(String bodbillno) {
		this.bodbillno = bodbillno;
	}

	@Column(name = "BODSHMFID", nullable = false, length = 30)
	public String getBodshmfid() {
		return this.bodshmfid;
	}

	public void setBodshmfid(String bodshmfid) {
		this.bodshmfid = bodshmfid;
	}

	@Column(name = "BODGDID", nullable = false, length = 24)
	public String getBodgdid() {
		return this.bodgdid;
	}

	public void setBodgdid(String bodgdid) {
		this.bodgdid = bodgdid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof YwBorderdetId))
			return false;
		YwBorderdetId castOther = (YwBorderdetId) other;

		return ((this.getBodsgcode() == castOther.getBodsgcode()) || (this
				.getBodsgcode() != null
				&& castOther.getBodsgcode() != null && this.getBodsgcode()
				.equals(castOther.getBodsgcode())))
				&& ((this.getBodbillno() == castOther.getBodbillno()) || (this
						.getBodbillno() != null
						&& castOther.getBodbillno() != null && this
						.getBodbillno().equals(castOther.getBodbillno())))
				&& ((this.getBodshmfid() == castOther.getBodshmfid()) || (this
						.getBodshmfid() != null
						&& castOther.getBodshmfid() != null && this
						.getBodshmfid().equals(castOther.getBodshmfid())))
				&& ((this.getBodgdid() == castOther.getBodgdid()) || (this
						.getBodgdid() != null
						&& castOther.getBodgdid() != null && this.getBodgdid()
						.equals(castOther.getBodgdid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getBodsgcode() == null ? 0 : this.getBodsgcode().hashCode());
		result = 37 * result
				+ (getBodbillno() == null ? 0 : this.getBodbillno().hashCode());
		result = 37 * result
				+ (getBodshmfid() == null ? 0 : this.getBodshmfid().hashCode());
		result = 37 * result
				+ (getBodgdid() == null ? 0 : this.getBodgdid().hashCode());
		return result;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return null;
	}

}
