package com.bfuture.app.saas.model;

// Generated 2011-12-7 14:38:38 by Hibernate Tools 3.2.2.GA

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.bfuture.app.basic.model.BaseObject;

/**
 * YwBorderdet generated by hbm2java
 * 订单明细（共15个字段）
 */
@Entity
@Table(name = "YW_BORDERDET")
public class YwBorderdet extends BaseObject implements java.io.Serializable {

	private YwBorderdetId id;		// 实例编码(bodsgcode) 订单编号(bodbillno) 门店编号(bodshmfid) 商品编码(bodgdid)
	private BigDecimal bodsl; 		// 订货数量
	private BigDecimal bodtax; 		// 税率
	private BigDecimal bodhsjj; 	// 含税金额
	private BigDecimal bodhsjjje; 	// 含税进价金额
	private String temp1;
	private String temp2;
	private String temp3;
	private String temp4;
	private String temp5;
	private Serializable bodtime;
	private String bodfile;
	
	// 辅助字段
	private String bodsgcode; // 实例编码
	private String bodbillno; // 订单编号
	private String bodshmfid; // 门店编号
	private String bodgdid;   // 商品编码

	public YwBorderdet() {
	}

	public YwBorderdet(YwBorderdetId id) {
		this.id = id;
	}

	public YwBorderdet(YwBorderdetId id, BigDecimal bodsl, BigDecimal bodtax,
			BigDecimal bodhsjj, BigDecimal bodhsjjje, String temp1,
			String temp2, String temp3, String temp4, String temp5,
			Serializable bodtime, String bodfile) {
		this.id = id;
		this.bodsl = bodsl;
		this.bodtax = bodtax;
		this.bodhsjj = bodhsjj;
		this.bodhsjjje = bodhsjjje;
		this.temp1 = temp1;
		this.temp2 = temp2;
		this.temp3 = temp3;
		this.temp4 = temp4;
		this.temp5 = temp5;
		this.bodtime = bodtime;
		this.bodfile = bodfile;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "bodsgcode", column = @Column(name = "BODSGCODE", nullable = false, length = 30)),
			@AttributeOverride(name = "bodbillno", column = @Column(name = "BODBILLNO", nullable = false, length = 32)),
			@AttributeOverride(name = "bodshmfid", column = @Column(name = "BODSHMFID", nullable = false, length = 30)),
			@AttributeOverride(name = "bodgdid", column = @Column(name = "BODGDID", nullable = false, length = 24)) })
	public YwBorderdetId getId() {
		return this.id;
	}

	public void setId(YwBorderdetId id) {
		this.id = id;
	}

	@Column(name = "BODSL", precision = 18, scale = 6)
	public BigDecimal getBodsl() {
		return this.bodsl;
	}

	public void setBodsl(BigDecimal bodsl) {
		this.bodsl = bodsl;
	}

	@Column(name = "BODTAX", precision = 5)
	public BigDecimal getBodtax() {
		return this.bodtax;
	}

	public void setBodtax(BigDecimal bodtax) {
		this.bodtax = bodtax;
	}

	@Column(name = "BODHSJJ", precision = 18, scale = 6)
	public BigDecimal getBodhsjj() {
		return this.bodhsjj;
	}

	public void setBodhsjj(BigDecimal bodhsjj) {
		this.bodhsjj = bodhsjj;
	}

	@Column(name = "BODHSJJJE", precision = 18, scale = 6)
	public BigDecimal getBodhsjjje() {
		return this.bodhsjjje;
	}

	public void setBodhsjjje(BigDecimal bodhsjjje) {
		this.bodhsjjje = bodhsjjje;
	}

	@Column(name = "TEMP1", length = 30)
	public String getTemp1() {
		return this.temp1;
	}

	public void setTemp1(String temp1) {
		this.temp1 = temp1;
	}

	@Column(name = "TEMP2", length = 30)
	public String getTemp2() {
		return this.temp2;
	}

	public void setTemp2(String temp2) {
		this.temp2 = temp2;
	}

	@Column(name = "TEMP3", length = 6)
	public String getTemp3() {
		return this.temp3;
	}

	public void setTemp3(String temp3) {
		this.temp3 = temp3;
	}

	@Column(name = "TEMP4", length = 6)
	public String getTemp4() {
		return this.temp4;
	}

	public void setTemp4(String temp4) {
		this.temp4 = temp4;
	}

	@Column(name = "TEMP5", length = 6)
	public String getTemp5() {
		return this.temp5;
	}

	public void setTemp5(String temp5) {
		this.temp5 = temp5;
	}

	@Column(name = "BODTIME")
	public Serializable getBodtime() {
		return this.bodtime;
	}

	public void setBodtime(Serializable bodtime) {
		this.bodtime = bodtime;
	}

	@Column(name = "BODFILE", length = 64)
	public String getBodfile() {
		return this.bodfile;
	}

	public void setBodfile(String bodfile) {
		this.bodfile = bodfile;
	}

	@Override
	public boolean equals(Object o) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public int hashCode() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return null;
	}

	// 辅助字段开始
	@Transient
	public String getBodsgcode() {
		return bodsgcode;
	}

	public void setBodsgcode(String bodsgcode) {
		this.bodsgcode = bodsgcode;
	}

	@Transient
	public String getBodbillno() {
		return bodbillno;
	}

	public void setBodbillno(String bodbillno) {
		this.bodbillno = bodbillno;
	}

	@Transient
	public String getBodshmfid() {
		return bodshmfid;
	}

	public void setBodshmfid(String bodshmfid) {
		this.bodshmfid = bodshmfid;
	}

	@Transient
	public String getBodgdid() {
		return bodgdid;
	}

	public void setBodgdid(String bodgdid) {
		this.bodgdid = bodgdid;
	}
	// 辅助字段结束
	

}
