package com.bfuture.app.saas.model;

// Generated 2011-12-7 14:38:38 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * YwPopinfoId generated by hbm2java
 */
@Embeddable
public class YwPopinfoId implements java.io.Serializable {

	private String popsequece;
	private String ppsgcode;
	private String pplb;
	private String ppgdid;
	private String ppsupid;
	private String ppmarket;
	private Date ppksrq;
	private Date ppjsrq;

	public YwPopinfoId() {
	}

	public YwPopinfoId(String popsequece, String ppsgcode, String pplb,
			String ppgdid, String ppsupid, String ppmarket, Date ppksrq,
			Date ppjsrq) {
		this.popsequece = popsequece;
		this.ppsgcode = ppsgcode;
		this.pplb = pplb;
		this.ppgdid = ppgdid;
		this.ppsupid = ppsupid;
		this.ppmarket = ppmarket;
		this.ppksrq = ppksrq;
		this.ppjsrq = ppjsrq;
	}

	@Column(name = "POPSEQUECE", nullable = false, length = 30)
	public String getPopsequece() {
		return this.popsequece;
	}

	public void setPopsequece(String popsequece) {
		this.popsequece = popsequece;
	}

	@Column(name = "PPSGCODE", nullable = false, length = 30)
	public String getPpsgcode() {
		return this.ppsgcode;
	}

	public void setPpsgcode(String ppsgcode) {
		this.ppsgcode = ppsgcode;
	}

	@Column(name = "PPLB", nullable = false, length = 24)
	public String getPplb() {
		return this.pplb;
	}

	public void setPplb(String pplb) {
		this.pplb = pplb;
	}

	@Column(name = "PPGDID", nullable = false, length = 24)
	public String getPpgdid() {
		return this.ppgdid;
	}

	public void setPpgdid(String ppgdid) {
		this.ppgdid = ppgdid;
	}

	@Column(name = "PPSUPID", nullable = false, length = 24)
	public String getPpsupid() {
		return this.ppsupid;
	}

	public void setPpsupid(String ppsupid) {
		this.ppsupid = ppsupid;
	}

	@Column(name = "PPMARKET", nullable = false, length = 30)
	public String getPpmarket() {
		return this.ppmarket;
	}

	public void setPpmarket(String ppmarket) {
		this.ppmarket = ppmarket;
	}

	@Column(name = "PPKSRQ", nullable = false, length = 7)
	public Date getPpksrq() {
		return this.ppksrq;
	}

	public void setPpksrq(Date ppksrq) {
		this.ppksrq = ppksrq;
	}

	@Column(name = "PPJSRQ", nullable = false, length = 7)
	public Date getPpjsrq() {
		return this.ppjsrq;
	}

	public void setPpjsrq(Date ppjsrq) {
		this.ppjsrq = ppjsrq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof YwPopinfoId))
			return false;
		YwPopinfoId castOther = (YwPopinfoId) other;

		return ((this.getPopsequece() == castOther.getPopsequece()) || (this
				.getPopsequece() != null
				&& castOther.getPopsequece() != null && this.getPopsequece()
				.equals(castOther.getPopsequece())))
				&& ((this.getPpsgcode() == castOther.getPpsgcode()) || (this
						.getPpsgcode() != null
						&& castOther.getPpsgcode() != null && this
						.getPpsgcode().equals(castOther.getPpsgcode())))
				&& ((this.getPplb() == castOther.getPplb()) || (this.getPplb() != null
						&& castOther.getPplb() != null && this.getPplb()
						.equals(castOther.getPplb())))
				&& ((this.getPpgdid() == castOther.getPpgdid()) || (this
						.getPpgdid() != null
						&& castOther.getPpgdid() != null && this.getPpgdid()
						.equals(castOther.getPpgdid())))
				&& ((this.getPpsupid() == castOther.getPpsupid()) || (this
						.getPpsupid() != null
						&& castOther.getPpsupid() != null && this.getPpsupid()
						.equals(castOther.getPpsupid())))
				&& ((this.getPpmarket() == castOther.getPpmarket()) || (this
						.getPpmarket() != null
						&& castOther.getPpmarket() != null && this
						.getPpmarket().equals(castOther.getPpmarket())))
				&& ((this.getPpksrq() == castOther.getPpksrq()) || (this
						.getPpksrq() != null
						&& castOther.getPpksrq() != null && this.getPpksrq()
						.equals(castOther.getPpksrq())))
				&& ((this.getPpjsrq() == castOther.getPpjsrq()) || (this
						.getPpjsrq() != null
						&& castOther.getPpjsrq() != null && this.getPpjsrq()
						.equals(castOther.getPpjsrq())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPopsequece() == null ? 0 : this.getPopsequece()
						.hashCode());
		result = 37 * result
				+ (getPpsgcode() == null ? 0 : this.getPpsgcode().hashCode());
		result = 37 * result
				+ (getPplb() == null ? 0 : this.getPplb().hashCode());
		result = 37 * result
				+ (getPpgdid() == null ? 0 : this.getPpgdid().hashCode());
		result = 37 * result
				+ (getPpsupid() == null ? 0 : this.getPpsupid().hashCode());
		result = 37 * result
				+ (getPpmarket() == null ? 0 : this.getPpmarket().hashCode());
		result = 37 * result
				+ (getPpksrq() == null ? 0 : this.getPpksrq().hashCode());
		result = 37 * result
				+ (getPpjsrq() == null ? 0 : this.getPpjsrq().hashCode());
		return result;
	}

}
