package com.bfuture.app.saas.model;

// Generated 2011-12-7 14:38:38 by Hibernate Tools 3.2.2.GA

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * YwZrstock generated by hbm2java
 */
@Entity
@Table(name = "YW_ZRSTOCK")
public class YwZrstock implements java.io.Serializable {

	private YwZrstockId id;
	private BigDecimal zskcsl;
	private BigDecimal zskcje;
	private String temp1;
	private String temp2;
	private String temp3;
	private String temp4;
	private String temp5;
	private Serializable zsgxtime;
	private String zsfile;

	public YwZrstock() {
	}

	public YwZrstock(YwZrstockId id) {
		this.id = id;
	}

	public YwZrstock(YwZrstockId id, BigDecimal zskcsl, BigDecimal zskcje,
			String temp1, String temp2, String temp3, String temp4,
			String temp5, Serializable zsgxtime, String zsfile) {
		this.id = id;
		this.zskcsl = zskcsl;
		this.zskcje = zskcje;
		this.temp1 = temp1;
		this.temp2 = temp2;
		this.temp3 = temp3;
		this.temp4 = temp4;
		this.temp5 = temp5;
		this.zsgxtime = zsgxtime;
		this.zsfile = zsfile;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "zssgcode", column = @Column(name = "ZSSGCODE", nullable = false, length = 30)),
			@AttributeOverride(name = "zssupid", column = @Column(name = "ZSSUPID", nullable = false, length = 24)),
			@AttributeOverride(name = "zsgdid", column = @Column(name = "ZSGDID", nullable = false, length = 24)),
			@AttributeOverride(name = "zsmfid", column = @Column(name = "ZSMFID", nullable = false, length = 30)),
			@AttributeOverride(name = "zsjyfs", column = @Column(name = "ZSJYFS", nullable = false, length = 30)) })
	public YwZrstockId getId() {
		return this.id;
	}

	public void setId(YwZrstockId id) {
		this.id = id;
	}

	@Column(name = "ZSKCSL", precision = 16)
	public BigDecimal getZskcsl() {
		return this.zskcsl;
	}

	public void setZskcsl(BigDecimal zskcsl) {
		this.zskcsl = zskcsl;
	}

	@Column(name = "ZSKCJE", precision = 16)
	public BigDecimal getZskcje() {
		return this.zskcje;
	}

	public void setZskcje(BigDecimal zskcje) {
		this.zskcje = zskcje;
	}

	@Column(name = "TEMP1", length = 16)
	public String getTemp1() {
		return this.temp1;
	}

	public void setTemp1(String temp1) {
		this.temp1 = temp1;
	}

	@Column(name = "TEMP2", length = 16)
	public String getTemp2() {
		return this.temp2;
	}

	public void setTemp2(String temp2) {
		this.temp2 = temp2;
	}

	@Column(name = "TEMP3", length = 16)
	public String getTemp3() {
		return this.temp3;
	}

	public void setTemp3(String temp3) {
		this.temp3 = temp3;
	}

	@Column(name = "TEMP4", length = 16)
	public String getTemp4() {
		return this.temp4;
	}

	public void setTemp4(String temp4) {
		this.temp4 = temp4;
	}

	@Column(name = "TEMP5", length = 16)
	public String getTemp5() {
		return this.temp5;
	}

	public void setTemp5(String temp5) {
		this.temp5 = temp5;
	}

	@Column(name = "ZSGXTIME")
	public Serializable getZsgxtime() {
		return this.zsgxtime;
	}

	public void setZsgxtime(Serializable zsgxtime) {
		this.zsgxtime = zsgxtime;
	}

	@Column(name = "ZSFILE", length = 64)
	public String getZsfile() {
		return this.zsfile;
	}

	public void setZsfile(String zsfile) {
		this.zsfile = zsfile;
	}

}
